### ISSUE TITLE
Headset found but not active

### ISSUE THREAD

**Issue by RodneyMcKay715** [auto94/HyperX-Cloud-2-Battery-Monitor#1]
The Headset is detected and working but shown as "found but not active"

The Headset is a Cloud II Wireless from HyperX but the HP version.

Is the Problem related to the manufacture?

![Screenshot 2023-12-16 215333](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/assets/26826816/73adcb95-9fd7-4e36-9cba-0a32cd659527)

**Comment by auto94** [comment]
Kind of, yes. The app still functions with my Kingston headset.

I assumed (well... hoped) that they wouldn't change the actual data being sent and received by the headset and without an actual HP headset I couldn't check.

I have one thing in mind that I can try, but if that doesn't work out, would you be willing to make a wireshark recording of the USB data transfers when you open the official NGENUITY app? I would prepare a step by step guide for you but it would probably still take roughly 15 minutes of your time, and you'd need to install wireshark + USBPcap.

**Comment by RodneyMcKay715** [comment]
Hey there, no trouble at all. Once i found which USBPcap was working i tried capturing as you wanted. I hope it gives you the information needed. Thanks for the effort. If you need anything feel free to contact me.

[HyperXCloud2Wireless_HP.zip](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/files/13698019/HyperXCloud2Wireless_HP.zip)

**Comment by auto94** [comment]
Hello again,

I think I've successfully reverse engineered the write/reads for the HP headset and have prepared a build for you to try.
Please give it a try when you have the chance and let me know if works. Fingers crossed!

Pre-release of the hp-fix branch download [here](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/releases/tag/Release_v1.4-alpha).

**Comment by RodneyMcKay715** [comment]
I just tested the build ,sadly the same message remains, shall i do another capture? Maybe i did something wrong on my end.

**Comment by auto94** [comment]
Yes, please do another capture and write your battery level at the time of recording. Also, if possible make a recording of you pressing the "Refresh" button in the battery monitor app. Thanks.

**Comment by auto94** [comment]
Hey,
any chance you could take a look? I'm about to add support for the HP Cloud II **Core** headset and it'd be great if I could bundle both together. Thanks!

**Comment by edimarpeterlini** [comment]
Hi, 
any chance to implement support for Cloud Stinger Core Wireless 7.1?

**Comment by RodneyMcKay715** [comment]
> Hey, any chance you could take a look? I'm about to add support for the HP Cloud II **Core** headset and it'd be great if I could bundle both together. Thanks!

Hey there, sorry for the long time of no reply. Life got in the way, as it always does. I started a capture, then opened Ngenuity and then checked the battery percentage. I can see activity in the capture. Maybe you can do something with this infomation. Just reply if you need anything further.

[Capture_HYPERXCLOUDII_WIRELESS.zip](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/files/14319313/Capture_HYPERXCLOUDII_WIRELESS.zip)

**Comment by auto94** [comment]
Thanks, @RodneyMcKay715. Totally understandable and I appreciate your help.

I've made another pre-release ([Release v1.4-beta](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/releases/tag/Release_v1.4-beta)), please try it when you get the chance. Going to be honest, I kinda feel the last one should've worked but I did make some small changes in this one.

If it still doesn't work, please make another recording of you pressing the refresh button a couple of times in the battery monitor, along with a screenshot of the app.
_________________________________________

@edimarpeterlini as for the Stinger, I've checked and I am not even sure it's possible. Does ngenuity show you the exact battery level? If it does I'll create a separate issue with some extra questions.

**Comment by RodneyMcKay715** [comment]
Hi, sadly it still tells me that the Headset has been found but is not active. Here is the capture:

[Capture_Ngenuity_App.zip](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/files/14322967/Capture_Ngenuity_App.zip)

I first clicked refresh in your app 3 times and then switched over to ngenuity and watched the battery percentage which is 84%.

![grafik](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/assets/26826816/f9b9cc77-ae40-46ef-b7ff-a7e5cc37e6ee)

**Comment by auto94** [comment]
Well I'm a bit stumped. In the recording, you can see in packet #32, the request gets made, in #33 the response is that it was successful and then in #38 the 7th byte of the return data is 0x54 which equals 84%. 

Judging from the screenshot, I believe you're on Windows 11? Can you try and run it in Win10 compatibility mode? Right click on the exe, properties, compatibility tab, run the program in compatibility mode for windows 10.

**Comment by auto94** [comment]
Try this now, added some extra reads. I'm optimistic.
[Release_v1.4-beta2](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/releases/tag/Release_v1.4-beta2)

Thanks for your help and patience!

**Comment by edimarpeterlini** [comment]
@auto94 
It doesn't just show loaded, medium level and low level.
I thought that in alternative software this could be resolved.

**Comment by RodneyMcKay715** [comment]
> Try this now, added some extra reads. I'm optimistic. [Release_v1.4-beta2](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/releases/tag/Release_v1.4-beta2)
> 
> Thanks for your help and patience!

Hi, sadly it did not work and i only got the option to run in compatibility with Windows 7 and 8, which both did not work. Ill try on a Windows 10 machine if that makes a difference and let you know. Thank you for your help with this.

**Comment by auto94** [comment]
Hello, I've got my hands on another headset and I've figured out the problem. Please try the new [pre-release](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/releases/tag/Release_v1.4). 

The problem was that the HID API returns multiple devices with the specified vendor id and product id. I thought that the easiest way to determine which device was the one that will respond with the battery level would be the one with the high usage_page. 
This was the case with the Kingston Cloud II Wireless and the HP Cloud II Core Wireless which both return the following devices:
|  Kingston/HP Core     | Usage page | Usage     |
| :----:        |    :----:   |         :----: |
| HID Device 1     | 12       | 1   |
| HID Device 2   | 65299        | 1      |

But the HP Cloud II Wireless returns 4 devices and it isn't the one with the highest usage page that responds but the one with the highest usage.

|  HP Wireless     | Usage page | Usage     |
| :----:        |    :----:   |         :----: |
| HID Device 1     | 12       | 1   |
| HID Device 2   | 65472        | 1      |
| HID Device 3   | 65424        | 771      |
| HID Device 4   | 65280        | 1      |

Unfortunately there isn't any property that would otherwise indicate which device is the one that actually responds so I had to make do with what I had available. If I had a better understanding of the USB/HID protocol maybe this could've been avoided but I think these are some vendor-specific usages/usage pages and are not publicly known (at least I didn't find much).

Either way, it should actually work now so give it a try :).

___________________________________________________________

@asynchronous98 I'm sorry I doubt that it's possible and if it is it's beyond my expertise. Sorry.

**Comment by RodneyMcKay715** [comment]
> Hello, I've got my hands on another headset and I've figured out the problem. Please try the new [pre-release](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/releases/tag/Release_v1.4).
> 
> The problem was that the HID API returns multiple devices with the specified vendor id and product id. I thought that the easiest way to determine which device was the one that will respond with the battery level would be the one with the high usage_page. This was the case with the Kingston Cloud II Wireless and the HP Cloud II Core Wireless which both return the following devices:
> Kingston/HP Core 	Usage page 	Usage
> HID Device 1 	12 	1
> HID Device 2 	65299 	1
> 
> But the HP Cloud II Wireless returns 4 devices and it isn't the one with the highest usage page that responds but the one with the highest usage.
> HP Wireless 	Usage page 	Usage
> HID Device 1 	12 	1
> HID Device 2 	65472 	1
> HID Device 3 	65424 	771
> HID Device 4 	65280 	1
> 
> Unfortunately there isn't any property that would otherwise indicate which device is the one that actually responds so I had to make do with what I had available. If I had a better understanding of the USB/HID protocol maybe this could've been avoided but I think these are some vendor-specific usages/usage pages and are not publicly known (at least I didn't find much).
> 
> Either way, it should actually work now so give it a try :).
> 
> @asynchronous98 I'm sorry I doubt that it's possible and if it is it's beyond my expertise. Sorry.

That's awesome. I just tested and it works perfectly. Sorry that you had to get another headset and that the Captures were not enough.
![grafik](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/assets/26826816/926c77b9-d5df-4d72-b54a-89f19c03422d)

**Comment by auto94** [comment]
Glad to hear and thank you for your help anyway!
Closing this issue now.
