### ISSUE TITLE
Cloud core wireless

### ISSUE THREAD

**Issue by xAGENTx** [auto94/HyperX-Cloud-2-Battery-Monitor#10]
Add Hyperx Cloud Core Wireless

**Comment by auto94** [comment]
Does the Core Wireless show the exact battery percentage in the ngenuity app?

**Comment by xAGENTx** [comment]
cloud core wireless doesnt support ngenuity app

**Comment by auto94** [comment]
Then I'm sorry but I doubt it can be done. It would be near impossible to figure out what data to send/read.
