### ISSUE TITLE
Headset found but not active

### ISSUE THREAD

**Issue by vos6434** [auto94/HyperX-Cloud-2-Battery-Monitor#11]
The app suddenly started having this issue after working for so long.
![image](https://github.com/user-attachments/assets/bf07d4b4-b247-4fb6-b002-1136bc161c44)

**Comment by auto94** [comment]
That's weird. 

1. I think I had a similar issue once but it was "fixed" by turning the headset off and on again. Did you try that and did it help?
2. Did you just update firmware or something similar maybe?
3. Do you have it set to automatically turn off after X minutes of inactivity? Did you maybe come back just when that time would be up maybe? Just thinking of things that could cause this.
4. Does it just completely not work anymore?

Thanks for any info you can share.

**Comment by vos6434** [comment]
Turning the headset off and replugging the wireless adapter doesn't fix the issue.
It's possible that I have updated my headsets firmware cant remember though.

EDIT: HyperX app didn't even see the headset and replugging the wireless adapter made it work this time.
