### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ShadowBlueee** [auto94/HyperX-Cloud-2-Battery-Monitor#12]
Hey man ive got a slight issue with this. after downloading and unzipping i try turning it on and get a error message that some file is missing. i tried this multiple times and am not sure if its even a problem in this app but any help would be great

**Comment by ShadowBlueee** [comment]
Release_v1.7a
the error message says i dont have 2 files
VCRUNTIME140.dll and MSVCP140.dll
and im on windows 10
i now understand this is not a problem on your side and im trying to fix it


čt 12. 12. 2024 v 16:44 odesílatel auto94 ***@***.***> napsal:

**Comment by ShadowBlueee** [comment]
i fixed the problem!

čt 12. 12. 2024 v 16:46 odesílatel Shadow Blue ***@***.***>
napsal:

**Comment by auto94** [comment]
Nice, I guess you had to install the c++ redistributable? I should probably list that as a requirement.

**Comment by ShadowBlueee** [comment]
yeah i did

čt 12. 12. 2024 v 16:50 odesílatel auto94 ***@***.***> napsal:
