### ISSUE TITLE
[Req] Cloud Alpha Wireless

### ISSUE THREAD

**Issue by GSNotifications** [auto94/HyperX-Cloud-2-Battery-Monitor#2]
Not sure what's needed to identify them with the application, but was wondering if it were possible for the 300hr Wireless version to be added?

**Comment by ArthurGamerHD** [comment]
Same Request, but looks like pretty easy to do.

**Comment by auto94** [comment]
Sorry, forgot to reply to your original request but looks like I got lucky and someone else already did the work. 

I should have the time to check the pull request and create a release+exe tomorrow. Just so you know I'm not ignoring this :)

**Comment by ArthurGamerHD** [comment]
yeah, i just looked for the device id, and which code it sends to the headset, and looking at response, the 3rd byte was 47, that was the exactly same number as reported by ngenuity as battery percentage,
since you did the hard part of creating the framework, all i had to do was put my half-baked hardcoded values on the buffer and everything worked fine 😝

**Comment by GSNotifications** [comment]
Ty, both of you <3

**Comment by ArthurGamerHD** [comment]
You're welcome,
since i already had to do for my own, 
not more fair than share back to the original repository

**Comment by auto94** [comment]
I made a [release](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/releases/tag/Release_v1.5). Let me know if the zip works if you have the time :). All credit to Arthur of course!

Thanks in advance.

**Comment by GSNotifications** [comment]
I built it earlier with his PR and it worked fine, using your release also works. Appreciate adding the support for it and for Arthur doing the work.

**Comment by ArthurGamerHD** [comment]
think this “issue” can be set to closed now

_maybe i will open a few QoL ones later_
