### ISSUE TITLE
[Req] Tray Icon

### ISSUE THREAD

**Issue by vos6434** [auto94/HyperX-Cloud-2-Battery-Monitor#9]
Could you add the option to use a battery icon instead of a coloured background with text?

**Comment by auto94** [comment]
I made a [pre-release](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/releases/tag/Release_v1.6) with this feature.
Let me know if you like it or you had something else in mind.  You can still customize the icon colors. 
![image](https://github.com/user-attachments/assets/659d9042-cd25-496d-93b3-8fc753f7988c)

Here are some examples:

![image](https://github.com/user-attachments/assets/a74d6343-c64b-43d2-95f6-de254bda61b9) 
![image](https://github.com/user-attachments/assets/53c7a908-78cb-4647-a004-0e660f0bf481)

**Comment by vos6434** [comment]
Its perfect, thank you!

Also is the text icon not cantered?

**Comment by auto94** [comment]
Yeah it's a bit off and I can make it a little better centered vertically but it still isn't going to be perfect for all numbers. Some are just a pixel wider or narrower than others so you can end up with a 1 pixel larger gap on one side. I've tried a few different fonts but I think they all have their issues tbh.

Left is with the new centering, right is the old one.

![image](https://github.com/user-attachments/assets/36b2a2a0-482d-438a-9454-5093f8e2b029)

I've updated the [pre-release v1.6](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/releases/tag/Release_v1.6).

I'll close this issue in a couple of days and promote the release if you don't find any other issues. Thanks.

**Comment by auto94** [comment]
Closing as solved, Release v1.6 promoted to current.
